Implement metric.calculate_unadaptability_metrics
mukobi/Unadaptable-Foundation-Models pull request #37
Opened 2024-04-24 07:38 UTC by ShinnosukeUesaka

Branch created from msw-dev. Waiting on #31 to merge.

I am retrieving baseline metrics from wandb by searching tag. I can also save/load from local file, if that's better. 

1. Implemented metric.calculate_unadaptability_metrics

- load in the val losses that already stored from fine-tuning the base model on wandb, then calculate the loss gap ratio

2. Logging evaluation losses during finetuning and save it to wandb

- The old script computed loss only at the end of finetune. Now, it logs and saves the evaluation loss every few steps. These losses are required to compute loss gap ratio.

3. Implement utils.check_base_results_saved

- Check wandb if baseline result is saved. Using "tag" to search.

5. Moved pretrain_score.run_benchmark to metrics.run_benchmark.

- The name pretrain does not make sense since we are running benchmark at different points in the script

2024-04-24 13:55 UTC, m-walters commented
@ShinnosukeUesaka Merged PR 31

2024-04-24 14:25 UTC, mukobi requested changes

2024-04-24 14:25 UTC, mukobi commented on main.py
> +from src.ufm import countermeasures, models, unadapt, utils, metrics, fine_tuning
You shouldn't use src.ufm if you have the latest changes and did `pip install -e .`

2024-04-24 14:25 UTC, mukobi commented on main.py
> +        name=cfg.basename if cfg.run_baseline else cfg.unadaptname,
Why the choice to specify a name? If you want it, you should probably include a random identifier along with it so we don't just end up with a bunch of runs all called e.g. `Pruning`

2024-04-24 14:25 UTC, mukobi commented on main.py
> +    metrics.calculate_unadaptability_metrics(ft_val_losses, wandb.config.basename, logger)
Yes, because it should be very fast to calculate the loss gap ratio, and it's a useful smoke test to make sure this is 0 for the base model.

2024-04-24 14:25 UTC, mukobi commented on src/ufm/fine_tuning.py
> +        trainer.save_model()
Does this save it to disk? We probably don't want this for now, just to keep it in memory. Would recommend either putting this within an if check for a new config flag, or else removing.

2024-04-24 19:46 UTC, m-walters commented on main.py
> +        os.makedirs(os.path.dirname(file_name), exist_ok=True)
please include a logger that this directory is being created/written to : )

2024-04-24 20:27 UTC, ShinnosukeUesaka commented on main.py
> +        #name=cfg.basename if cfg.get('basename') else None,
@mukobi 
I think we can name the runs. It doesn't take that much effort to create a new name every run.

2024-04-24 20:30 UTC, ShinnosukeUesaka commented on main.py
> +    )
I refactored the code so that we have separate pipeline when cfg.run_baseline == True.
Line 41

2024-04-24 20:33 UTC, ShinnosukeUesaka commented on configs/base_config.yaml
> +run_baseline: true # If True, calculates metric on the base model. If False, applies unadapt and calculate metric on anadapt model
Ok I will keep it for now.

2024-04-25 18:15 UTC, mukobi commented on main.py
> +        #name=cfg.basename if cfg.get('basename') else None,
But should include a random identifier with it so we can reference "Pruning-4042" and not just have a bunch of runs called "Pruning".

2024-04-25 18:54 UTC, ShinnosukeUesaka commented on main.py
> +    )
@m-walters

2024-05-01 03:27 UTC, m-walters commented on main.py
> +    )
@ShinnosukeUesaka 
I made a PR to be merged into this branch:
https://github.com/mukobi/Unadaptable-Foundation-Models/pull/44
It also resolves this comment

2024-05-11 03:08 UTC, merged